---

# Worlds path
worlds-path: 'C:\Users\Nam\Desktop\SharedData\worlds'

# Plugins path
plugins-path: 'C:\Users\Nam\Desktop\SharedData\plugins'

# Inventory players
inventory-players:

  # Enable inventory players path
  enable: true

  # Path
  path: 'C:\Users\Nam\Desktop\SharedData\inventory-players'

...